name: TEST AND DEPLOY
on:
  #  push:
  #   branches:
  #     [ main ]
 pull_request:
    types:
      - closed
    branches:
      - main
#  workflow_dispatch:
   
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Assign or Get TAG
      id: get-tag
      uses: delta-bravo277/git-tag-final@main
      # with:
      #  token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
      
      # uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: none
        
    - name: Print GIT tag
      id: determine-tag
      env:
        NEW_TAG: ${{ steps.get-tag.outputs.tag }}
        PART: ${{ steps.get-tag.outputs.part }}
      run: |
        echo $NEW_TAG
        echo $PART
